@host = http://localhost:3001
@baseUrl = {{host}}/api

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@gmail.com",
  "password": "admin123"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Refresh Token
# @name doRefreshToken
POST {{baseUrl}}/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.$.data.tokens.refreshToken}}"
}

### Get Current User (requires auth)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{login.response.body.$.data.tokens.accessToken}}
