export enum ErrorCode {
  VALIDATION_ERROR = 'ERR_VALIDATION_001',
  INVALID_INPUT = 'ERR_VALIDATION_002',

  UNAUTHORIZED = 'ERR_AUTH_001',
  TOKEN_EXPIRED = 'ERR_AUTH_002',
  INVALID_TOKEN = 'ERR_AUTH_003',
  INVALID_CREDENTIALS = 'ERR_AUTH_004',
  USER_NOT_FOUND = 'ERR_AUTH_005',

  FORBIDDEN = 'ERR_AUTHZ_001',
  INSUFFICIENT_PERMISSIONS = 'ERR_AUTHZ_002',

  RESOURCE_NOT_FOUND = 'ERR_NOTFOUND_001',

  UNIQUE_CONSTRAINT = 'ERR_CONFLICT_001',
  FOREIGN_KEY_CONSTRAINT = 'ERR_CONFLICT_002',
  RECORD_CONFLICT = 'ERR_CONFLICT_003',

  DB_UNIQUE_CONSTRAINT = 'ERR_DB_001',
  DB_FOREIGN_KEY_CONSTRAINT = 'ERR_DB_002',
  DB_RECORD_NOT_FOUND = 'ERR_DB_003',
  DB_VALIDATION_FAILED = 'ERR_DB_004',

  INTERNAL_ERROR = 'ERR_INTERNAL_001',
  SERVICE_UNAVAILABLE = 'ERR_INTERNAL_002',
}
